<template>
  <div>
    <h2>Privacy Policy</h2>
    <h3>Overview</h3>
    <p>Limited Audience is fully committed to protecting the privacy of consumers of its interactive products and services. We want to contribute to providing a safe and secure environment for everyone.</p>
    <p>This privacy policy extends to all Limited Audience operated sites including all of our Internet-accessible Limited Audience branded services, hereafter called simply "Limited Audience". This Privacy Policy is to inform you, as a welcome visitor to the world of Limited Audience, what kinds of information we may gather about you when you visit; how we may use that information; whether we disclose it to anyone, and the choices you have regarding our use of, and your ability to correct, the information we hold.</p>
    <p>Finally, please note that this policy applies only to Limited Audience built and maintained Web sites that carry the Limited Audience brand, and not to any other company or organizations' Web sites to which we link or have affiliated to.</p>
    <p>In general, our service automatically gathers certain usage information like the numbers and frequency of visitors, very much like television ratings that tell the networks how many people tuned in to a program. We only use such data in the aggregate. This collective data helps us determine how much our customers use parts of a given site. This allows us to improve our services and ensure that they are as appealing as they can be. </p>
    <p>For example, Limited Audience may use a technology nicknamed "cookies" that tells us how and when pages in our site are visited, and by how many people. Such cookies do not collect personally identifiable information and we do not combine information collected through cookies with other personally identifiable information to tell us who you are or even what your screen name or e-mail address is. </p>
    <h3>Information about you that you provide us</h3>
    <p>Limited Audience does not ask you to provide any personal information to us, beyond an email address when you choose to contact us. We do not store this email address or add it to any mailing lists. We only use it to answer your queries.</p>
    <p>We provide links to third party sites that sell our content. These sites will ask you for personal information to complete transactions. This information stays with them and is not passed back to us. Please check their own privacy policies to see how they handle your data.</p>
    <h3>Disclosure</h3>
    <p>We do not use or disclose information about your individual visits to any Limited Audience operated site or any information that you may give us, such as your name, address, email address or telephone number, to any outside company or organisation unless we are legally requested to do so as part of any Government Investigation or to protect or enforce our own legal rights under any agreement which has been breached, or we believe has been breached, or to protect any and all copyright infringements. In such events Limited Audience shall only release information when Limited Audience believe it appropriate to and then only to the relevant authority. </p>
    <p>Limited Audience does not request, or knowingly collect identifiable information from children under the age of 18. Limited Audience does not knowingly use or share personal information from users under the age of 18 with third parties. Limited Audience does not offer children any promotions involving games, prizes, or any other activity that would induce a child to divulge personal information.</p>
    <h3>Data Protection</h3>
    <p>Limited Audience and its associated websites employ the latest and best techniques available for protecting its systems from intrusion by unauthorized individuals, and both we and our associated webmasters and billing providers are constantly upgrading security as better methods become available. All information is stored behind firewalls and other sophisticated security systems. All data centres housing hardware utilise state-of-the-art physical security measures to prevent unauthorized access to any facility.</p>
    <h3>Limited Audience Privacy Policy Changes</h3>
    <p>If we decide to change our privacy policy for Limited Audience, we will post those changes here so that you will always know what information we gather, how we might use that information and whether we will disclose it to anyone. As a user of our services you may therefore have complete faith and confidence in all your dealings with us.</p>
    <p><em>Last updated: October 14, 2017.</em></p>
  </div>  
</template>
